export class UserReg
{
    firstName?:string; 
    lastName?:string;
    email?:string;
    address1?:string;
    address2?:string;
    city?:string;
    state?:string
    pincode?:any;
    aadharCard?:any;
    panCard?:any;
    certificate?:any;
    traderLicense?:any;
    password?:string;
    roletype?:string;
    accountNo?:string;
    ifscCode?:string; 
}